awful.util.spawn("/usr/libexec/openbox-xdg-autostart AWESOME")
awful.util.spawn("/usr/bin/xcompmgr -c")
awful.util.spawn("/usr/bin/blueman-applet")
awful.util.spawn("/usr/bin/pam-panel-icon")
awful.util.spawn("/usr/bin/system-config-printer-applet")
awful.util.spawn("/usr/bin/firewall-applet")
awful.util.spawn("/usr/bin/gpk-update-icon")
awful.util.spawn("/usr/libexec/gdu-notification-daemon")
